name: Terraform Demo
on:
  workflow_dispatch:
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
        - name: Local Stack Docker Setup
          run: |
           docker run -d -t -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
           docker ps
           echo "Wait 10s"
           sleep 10
           echo "tflocal"
           python3 -m pip install terraform-local

           
            
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Terraform Plan
          run: |
           tflocal init
           tflocal plan
           tflocal apply -auto-approve
          
            
       
