name: Terraform Demo
on:
  workflow_dispatch:
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
        - name: Local Stack Docker Setup
          run: |
           python3 -m pip install localstack
           localstack start
            
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Terraform Plan
          run: terraform plan 
          
            
       
