name: Terraform Demo
on:
  workflow_dispatch:
jobs:
  CI-CD:
    runs-on: ubuntu-latest
    permissions: 
      packages: write
    steps:
        - name: Local Stack Docker Setup
          run: |
            docker run --rm -t -p 4566:4566 -p 4510-4559:4510-4559 localstack/localstack
            sleep 20
            docker ps
            
        - name: Checkout Code
          uses: actions/checkout@v3

        - name: Terraform Plan
          run: terraform plan 
          
            
       
