on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo '${{(github.event.issue.body) }}'
              '${{ toJSON(github.event.issue.body) }}' >> demo.txt
              cat demo.txt
              source demo.txt
              echo "Name=name" >> $GITHUB_ENV
              echo ${{env.Name }}
