on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
             echo '${{ toJSON(github.event.issue.body) }}'
             echo "body = ${{ toJSON(github.event.issue.body) }}" >> GITHUB_ENV
             echo  $body.msg
          
