on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo '${{ toJSON(github.event.issue.body) }}' >> out.txt
              ls
              cat out.txt
              sleep 2
              rm out.txt
              ls-al
             
