on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              echo '${{ toJSON(github.event.issue.body) }}'
              echo "data=${{ toJSON(github.event.issue.body)}}" >> "$GITHUB_ENV"
              echo "${{env.data}}"
               echo " name is : ${{env.data}}.*.name "
                echo "${{env.data}}.name"
                echo " name :(${{env.data}}).name"
