on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
             echo '${{ toJSON(github.event.issue.body) }}'
               echo "data=${{ toJSON(github.event.issue.body) }}" >> "$GITHUB_ENV"
               echo "join"
               echo ${{join(env.data.*.name, ',') }}
               echo "Comment body"
                  echo '${{toJSON(github.event.issue.body.*.name) }}'
             
          
