on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo '${{(github.event.issue.body) }}'
              echo "Name is ${{(github.event.issue.body.*.name) }} "
                  echo "Name is 18  ${{(github.event.issue.body).*.name) }}"
                      echo "Name is ${{(github.event.issue.body.name) }}"
              echo "Name=${{(github.event.issue.body.*.name) }}" >> "$GITHUB_ENV"
              echo "Msg=${{(github.event.issue.body }}" >> "$GITHUB_ENV"
              echo "test"
              echo "Hello ${{env.Name }} and msg is ${{env.Msg.*.msg}} and  (${{env.Msg}}.*msg) is (${{env.Msg}}.msg)"
