on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              
              echo "NAme: ${{(github.event.issue.body) }}.*.name "
              echo  ' ${{ toJSON(github.event.issue.body.issue_comment.comments) }} '
              echo " name is ${{ join ( (github.event.issue.comments).*.name, ',' ) }}
              echo " name was ${{ join (github.event.issue.comments.*.name, ',' ) }}
