on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo  ' ${{ github.event.issue.body.issue_comment.comments}} '
              echo " name is ${{ github.event.issue.comments.*.name }}
