on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo " body : (github.event.issue.body) "
              echo " body name : (github.event.issue.body).*.name "
              echo "comment is  (github.event.issue.body.comment.*.name) "
              echo "NAme: ${{fromJSON(github.event.issue.body)}} "
             
