on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
jobs:
    demo:
        runs-on: ubuntu-latest
        steps:
            - name: Parse
              env:
                data: ${{fromJSON(github.event.issue)}}
                issue: ${{fromJSON(github.event.issue.number)}}
                body: ${{fromJSON(github.event.issue.body)}}
                ibody: ${{(github.event.issue.body)}}
                no: ${{(github.event.issue.number)}}
              run: |
                  echo  $data $issue $no $ibody
          
