on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
          - closed
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: |
              pwd
              echo '${{ toJSON(github.event.issue.body) }}'
              echo '${{(github.event.issue.body) }}'
         
              echo "Name=${{(github.event.issue.body.*.name) }}" >> "$GITHUB_ENV"
              echo "Msg=${{(github.event.issue.body.msg) }}" >> "$GITHUB_ENV"
              echo "test"
              echo "Hello ${{env.Name }} and msg is ${{env.Msg }}
