on: 
    workflow_dispatch:
    issues:
        types:
          - opened
          - edited
jobs:
    demo:
        runs-on: ubuntu-latest
        continue-on-error: true
        steps:
          - name: Dump GitHub context
            run: echo '${{ toJSON(github) }}'
          - name:  Dump job context
            run: echo '${{ toJSON(job) }}'
          - name: Dump steps context
            run: echo '${{ toJSON(steps) }}'
          
